//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à et.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a type of save :.
        /// </summary>
        internal static string Choose_a_type_of_save__ {
            get {
                return ResourceManager.GetString("Choose a type of save :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App is closing...
        /// </summary>
        internal static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a backup.
        /// </summary>
        internal static string Create_a_backup {
            get {
                return ResourceManager.GetString("Create a backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a work.
        /// </summary>
        internal static string CreateWork {
            get {
                return ResourceManager.GetString("CreateWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chose to create a work.
        /// </summary>
        internal static string CreateWorkChoosen {
            get {
                return ResourceManager.GetString("CreateWorkChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work deleted successfully.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a work.
        /// </summary>
        internal static string DeleteWork {
            get {
                return ResourceManager.GetString("DeleteWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chose to delete a work.
        /// </summary>
        internal static string DeleteWorkChosen {
            get {
                return ResourceManager.GetString("DeleteWorkChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        internal static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to EasySave !.
        /// </summary>
        internal static string EasySave {
            get {
                return ResourceManager.GetString("EasySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Leave empty to keep the same).
        /// </summary>
        internal static string EmptyForSame {
            get {
                return ResourceManager.GetString("EmptyForSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string Englisht {
            get {
                return ResourceManager.GetString("Englisht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a file source :.
        /// </summary>
        internal static string Enter_a_file_source__ {
            get {
                return ResourceManager.GetString("Enter a file source :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a file target :.
        /// </summary>
        internal static string Enter_a_file_target__ {
            get {
                return ResourceManager.GetString("Enter a file target :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a name :.
        /// </summary>
        internal static string Enter_a_name__ {
            get {
                return ResourceManager.GetString("Enter a name :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a name.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a source folder.
        /// </summary>
        internal static string EnterSource {
            get {
                return ResourceManager.GetString("EnterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a target folder.
        /// </summary>
        internal static string EnterTarget {
            get {
                return ResourceManager.GetString("EnterTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a type (1. Complete, 2. Differential).
        /// </summary>
        internal static string Entertype {
            get {
                return ResourceManager.GetString("Entertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute a backup.
        /// </summary>
        internal static string Execute_a_backup {
            get {
                return ResourceManager.GetString("Execute a backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of work transfer.
        /// </summary>
        internal static string ExecuteEnded {
            get {
                return ResourceManager.GetString("ExecuteEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute a work.
        /// </summary>
        internal static string ExecuteWork {
            get {
                return ResourceManager.GetString("ExecuteWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chose to execute a work.
        /// </summary>
        internal static string ExecuteWorkChossen {
            get {
                return ResourceManager.GetString("ExecuteWorkChossen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute all works.
        /// </summary>
        internal static string ExecuteWorks {
            get {
                return ResourceManager.GetString("ExecuteWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You chose to execute all works..
        /// </summary>
        internal static string ExecuteWorksChosen {
            get {
                return ResourceManager.GetString("ExecuteWorksChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executed successfully.
        /// </summary>
        internal static string ExecutingSuccess {
            get {
                return ResourceManager.GetString("ExecutingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running.
        /// </summary>
        internal static string ExecutingWork {
            get {
                return ResourceManager.GetString("ExecutingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à failed.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string Français {
            get {
                return ResourceManager.GetString("Français", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get started today.
        /// </summary>
        internal static string Get_started_today {
            get {
                return ResourceManager.GetString("Get started today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid index..
        /// </summary>
        internal static string InvalidIndex {
            get {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid option..
        /// </summary>
        internal static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid type, please modify your work then try again.
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language changed.
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work modified successfully.
        /// </summary>
        internal static string ModificationSuccess {
            get {
                return ResourceManager.GetString("ModificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifiying work.
        /// </summary>
        internal static string ModifiyingWork {
            get {
                return ResourceManager.GetString("ModifiyingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify a backup.
        /// </summary>
        internal static string Modify_a_backup {
            get {
                return ResourceManager.GetString("Modify a backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify a work.
        /// </summary>
        internal static string ModifyWork {
            get {
                return ResourceManager.GetString("ModifyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No work created to date.
        /// </summary>
        internal static string NoWorkCreated {
            get {
                return ResourceManager.GetString("NoWorkCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a backup to execute :.
        /// </summary>
        internal static string Please_choose_a_backup_to_execute__ {
            get {
                return ResourceManager.GetString("Please choose a backup to execute :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a backup to modify :.
        /// </summary>
        internal static string Please_choose_a_backup_to_modify__ {
            get {
                return ResourceManager.GetString("Please choose a backup to modify :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please complete the informations below :.
        /// </summary>
        internal static string Please_complete_the_informations_below__ {
            get {
                return ResourceManager.GetString("Please complete the informations below :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose an action to execute..
        /// </summary>
        internal static string PleaseChooseAction {
            get {
                return ResourceManager.GetString("PleaseChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a work.
        /// </summary>
        internal static string PleaseSelectWork {
            get {
                return ResourceManager.GetString("PleaseSelectWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save type.
        /// </summary>
        internal static string SaveType {
            get {
                return ResourceManager.GetString("SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source folder.
        /// </summary>
        internal static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source folder does not exist.
        /// </summary>
        internal static string SourceNotExists {
            get {
                return ResourceManager.GetString("SourceNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target folder.
        /// </summary>
        internal static string TargetFolder {
            get {
                return ResourceManager.GetString("TargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue.
        /// </summary>
        internal static string ToContinue {
            get {
                return ResourceManager.GetString("ToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Works created limit has been reached.
        /// </summary>
        internal static string TooMuchWorks {
            get {
                return ResourceManager.GetString("TooMuchWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To quit, press : q.
        /// </summary>
        internal static string ToQuit {
            get {
                return ResourceManager.GetString("ToQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type a new name.
        /// </summary>
        internal static string TypeNewName {
            get {
                return ResourceManager.GetString("TypeNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type a new save type (1. Complete, 2. Differential).
        /// </summary>
        internal static string TypeNewSaveType {
            get {
                return ResourceManager.GetString("TypeNewSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type a new source folder.
        /// </summary>
        internal static string TypeNewSource {
            get {
                return ResourceManager.GetString("TypeNewSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type a new target folder.
        /// </summary>
        internal static string TypeNewTarget {
            get {
                return ResourceManager.GetString("TypeNewTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome on Easysave.
        /// </summary>
        internal static string Welcome_on_Easysave {
            get {
                return ResourceManager.GetString("Welcome on Easysave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your precedent backup :.
        /// </summary>
        internal static string Your_precedent_backup__ {
            get {
                return ResourceManager.GetString("Your precedent backup :", resourceCulture);
            }
        }
    }
}
